GET http://localhost:3333/tweets HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjllMmViNzllLWUyNzYtNGE0Ni04NDQ1LTE3ODc1ODk4OWZhYiIsIm5vbWUiOiJqb2FuYSIsImVtYWlsIjoiam9hbmFAdGVzdGUuY29tIiwiaWF0IjoxNzA0NzYyNDI3LCJleHAiOjE3MDQ3NjYwMjd9.pokQQOwmfAoUrlVf8UaI7GkxiPQVrw7rI9zKk1hzKVo